### ISSUE TITLE
Physical keys blocked by jQuery.NumPad

### ISSUE THREAD

**Issue by kq01526** [kabachello/jQuery.NumPad#6]
@kabachello :

Judging from your demos:

http://a.kabachnik.info/numeric-keypad-for-jquerymobile.html
http://a.kabachnik.info/jquery-numpad.html

it looks like the physical keys of a physical keyboard do no longer work once the jQuery.NumPad has popped up. It seems to block phsysical keyboard input.

Why can't the jQuery.NumPad be used simultaneously with a physical keyboard?

Regards

**Comment by kabachello** [comment]
Hi! 

Initializing the numpad currently makes the input element it is being initialized for (the "target") read-only. This makes things simpler as we do not need to sync the value of the target input and the "display" of the numpad in sync in both directions. 

There is still a simple solution for your issue. You can give the "display" of the numpad focus automatically - each time the numpad is being opened. Just add the following lines to the parameter when instantiating the numpad:

```
onKeypadOpen: function(){
  $(this).find('.nmpd-display').focus();
} 
```
